apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  #annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
  #  nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /v1/login
        #pathType: Prefix
        backend:
          serviceName: authservice-service
          servicePort: 80
      - path: /
        backend:
          serviceName: frontend-service
          servicePort: 80

