apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /payment/(.*)
        backend:
          serviceName: payment-service
          servicePort: 80
      - path: /auth/(.*)
        backend:
          serviceName: authservice-service
          servicePort: 80
      - path: /task/(.*)
        backend:
          serviceName: taskservice-service
          servicePort: 80
      - path: /(.*)
        backend:
          serviceName: frontend-service
          servicePort: 80
