apiVersion: apps/v1
kind: Deployment
metadata:
        name: taskexecutor-deployment
        labels:
                app: taskexecutor
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: taskexecutor
        template:
                metadata:
                        labels:
                                app: taskexecutor
                spec:
                        containers:
                        - name: rosaexecutor
                          image: rpwtouk/rosaexecutor:v0.0.5
                          env:
                          - name: BROKER_USER
                            value: "guest"
                          - name: BROKER_PASSWORD
                            value: "guest"
                          - name: BROKER_ADDRESS
                            value: "rabbitmq-service"
                          ports:
                          - containerPort: 80
